#!/bin/bash
# 🐋 WALRUS AGENTS - Sui Contract Deployment Script
# This script deploys the Move smart contracts to Sui testnet

set -e  # Exit on error

echo "🐋 WALRUS AGENTS - Contract Deployment"
echo "========================================"
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if Sui CLI is installed
if ! command -v sui &> /dev/null; then
    echo -e "${RED}❌ Sui CLI not found. Please install it first:${NC}"
    echo "   brew install sui"
    echo "   Or visit: https://docs.sui.io/guides/developer/getting-started/sui-install"
    exit 1
fi

echo -e "${GREEN}✓ Sui CLI found: $(sui --version)${NC}"
echo ""

# Check if wallet is configured
if ! sui client active-address &> /dev/null; then
    echo -e "${YELLOW}⚠️  No active Sui wallet found${NC}"
    echo "   Setting up new wallet..."
    sui client new-address ed25519
fi

ACTIVE_ADDRESS=$(sui client active-address)
echo -e "${BLUE}📍 Active Address: $ACTIVE_ADDRESS${NC}"
echo ""

# Check current network
CURRENT_ENV=$(sui client active-env)
echo -e "${BLUE}🌐 Current Network: $CURRENT_ENV${NC}"

# Switch to testnet if needed
if [ "$CURRENT_ENV" != "testnet" ]; then
    echo -e "${YELLOW}⚠️  Switching to testnet...${NC}"
    sui client switch --env testnet || sui client new-env --alias testnet --rpc https://fullnode.testnet.sui.io:443
    sui client switch --env testnet
    echo -e "${GREEN}✓ Switched to testnet${NC}"
fi
echo ""

# Check gas balance
echo -e "${BLUE}💰 Checking gas balance...${NC}"
BALANCE=$(sui client gas --json | grep -o '"value":[0-9]*' | head -1 | grep -o '[0-9]*' || echo "0")
BALANCE_SUI=$((BALANCE / 1000000000))

if [ $BALANCE_SUI -lt 1 ]; then
    echo -e "${RED}❌ Insufficient gas (${BALANCE_SUI} SUI)${NC}"
    echo ""
    echo "Please get testnet SUI tokens from faucet:"
    echo "   https://faucet.testnet.sui.io/"
    echo ""
    echo "Or run: sui client faucet"
    exit 1
fi

echo -e "${GREEN}✓ Gas balance: ${BALANCE_SUI} SUI${NC}"
echo ""

# Build the Move package
echo -e "${BLUE}🔨 Building Move package...${NC}"
cd move
sui move build

if [ $? -ne 0 ]; then
    echo -e "${RED}❌ Build failed${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Build successful${NC}"
echo ""

# Deploy to testnet
echo -e "${BLUE}🚀 Deploying contracts to Sui testnet...${NC}"
DEPLOY_OUTPUT=$(sui client publish --gas-budget 100000000 --json)

if [ $? -ne 0 ]; then
    echo -e "${RED}❌ Deployment failed${NC}"
    echo "$DEPLOY_OUTPUT"
    exit 1
fi

echo -e "${GREEN}✓ Deployment successful!${NC}"
echo ""

# Parse deployment results
PACKAGE_ID=$(echo $DEPLOY_OUTPUT | grep -o '"packageId":"[^"]*"' | cut -d'"' -f4)
REGISTRY_ID=$(echo $DEPLOY_OUTPUT | grep -o '"objectId":"0x[^"]*"' | head -1 | cut -d'"' -f4)
POOL_ID=$(echo $DEPLOY_OUTPUT | grep -o '"objectId":"0x[^"]*"' | tail -1 | cut -d'"' -f4)

# Create deployment record
cd ..
cat > deployed-addresses.json << EOF
{
  "network": "testnet",
  "deployedAt": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "deployer": "$ACTIVE_ADDRESS",
  "packageId": "$PACKAGE_ID",
  "contracts": {
    "agentRegistry": {
      "moduleId": "${PACKAGE_ID}::agent_registry",
      "sharedObjectId": "$REGISTRY_ID"
    },
    "trainingRewards": {
      "moduleId": "${PACKAGE_ID}::training_rewards",
      "sharedObjectId": "$POOL_ID"
    }
  },
  "explorer": {
    "package": "https://suiscan.xyz/testnet/object/${PACKAGE_ID}",
    "registry": "https://suiscan.xyz/testnet/object/${REGISTRY_ID}",
    "pool": "https://suiscan.xyz/testnet/object/${POOL_ID}"
  }
}
EOF

echo "📦 Deployment Summary"
echo "===================="
echo ""
echo -e "${GREEN}Package ID:${NC} $PACKAGE_ID"
echo -e "${GREEN}Agent Registry:${NC} $REGISTRY_ID"
echo -e "${GREEN}Reward Pool:${NC} $POOL_ID"
echo ""
echo -e "${BLUE}🔍 View on Explorer:${NC}"
echo "   https://suiscan.xyz/testnet/object/$PACKAGE_ID"
echo ""
echo -e "${GREEN}✅ Deployment details saved to deployed-addresses.json${NC}"
echo ""

# Update constants.ts with new addresses
echo -e "${BLUE}📝 Updating constants.ts...${NC}"

cat > constants.ts << EOF
// 🐋 WALRUS AGENTS - Configuration Constants
// Auto-generated by deploy.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

export const SUI_NETWORK = 'testnet';
export const SUI_RPC_URL = 'https://fullnode.testnet.sui.io:443';

// Deployed contract addresses
export const CONTRACTS = {
  PACKAGE_ID: '$PACKAGE_ID',
  AGENT_REGISTRY: '$REGISTRY_ID',
  REWARD_POOL: '$POOL_ID',
};

// Walrus Protocol Configuration
export const WALRUS_CONFIG = {
  PUBLISHER_URL: 'https://publisher.walrus-testnet.walrus.space',
  AGGREGATOR_URL: 'https://aggregator.walrus-testnet.walrus.space',
  EPOCHS: 5, // Number of epochs to store (5-10 recommended)
};

// BlockBerry API (Sui Mainnet Data)
export const BLOCKBERRY_API = {
  BASE_URL: 'https://api.blockberry.one/sui/v1',
  API_KEY: 'wfpnqfQSoQNJRRSZb3T3Yei6vaD3ZR',
};

// External APIs
export const EXTERNAL_APIS = {
  GEMINI_AI: import.meta.env.VITE_GEMINI_API_KEY || '',
  TWELVE_DATA: import.meta.env.VITE_TWELVE_DATA_KEY || '',
  NEWS_API: import.meta.env.VITE_NEWS_API_KEY || '',
};

// Agent Roles
export const AGENT_ROLES = [
  { id: 'a0', name: 'Walrus Commander', role: 'Coordinator', emoji: '🐋' },
  { id: 'a1', name: 'Eagleton Skywatcher', role: 'Observer', emoji: '🦅' },
  { id: 'a2', name: 'Athena Nightwing', role: 'Analyst', emoji: '🦉' },
  { id: 'a3', name: 'Reynard Swift', role: 'Executor', emoji: '🦊' },
  { id: 'a4', name: 'Ursus Guardian', role: 'Validator', emoji: '🐻' },
  { id: 'a5', name: 'Luna Mysticfang', role: 'Oracle', emoji: '🐺' },
  { id: 'a6', name: 'Corvus Messenger', role: 'Communicator', emoji: '🐦' },
];

// Cache settings
export const CACHE_PREFIX = 'walrus_cache_';
export const CACHE_EXPIRY = 5 * 60 * 1000; // 5 minutes
EOF

echo -e "${GREEN}✓ constants.ts updated${NC}"
echo ""

echo -e "${GREEN}🎉 Deployment Complete!${NC}"
echo ""
echo "Next steps:"
echo "1. Test contract interaction: npm run test:contracts"
echo "2. Setup Walrus storage: ./setup-walrus.sh"
echo "3. Start the app: npm run dev"
echo ""
